version: '3'

services:
  web:
    build: .
    command: uv run manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - /app/.venv
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - CELERY_BROKER_URL=redis://redis:6379/0

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  celery_worker:
    build: .
    command: uv run celery -A yt_check worker --loglevel=info
    volumes:
      - .:/app
      - /app/.venv
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - CELERY_BROKER_URL=redis://redis:6379/0

  celery_beat:
    build: .
    command: uv run celery -A yt_check beat --loglevel=info
    volumes:
      - .:/app
      - /app/.venv
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - CELERY_BROKER_URL=redis://redis:6379/0
  flower:
    build: .
    command: uv run celery -A yt_check flower --port=5555
    ports:
      - "5555:5555"
    depends_on:
      - redis
    volumes:
      - .:/app
      - /app/.venv
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - CELERY_BROKER_URL=redis://redis:6379/0