# Generated by Django 5.2.1 on 2025-05-19 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0002_channel_is_live'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='live_stream_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
