# Generated by Django 5.2.1 on 2025-05-19 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0003_channel_live_stream_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='live_stream_count',
        ),
        migrations.AddField(
            model_name='channel',
            name='current_streams_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
